name: update_db
on:
  workflow_dispatch:
    # 允许在 github 网站上手动触发，这里啥也不用写好像
  
  push:
    # 推送时也触发一下
    
  schedule:
    # cron: 'mm h d m d' # 分时日月周
    - cron: '16 0 * * 5' # 东八区 周五 早八点十六
    - cron: '28 0 * * 5'
    - cron: '38 0 * * 5'
    - cron: '50 0 * * 5'
    - cron: '55 0 * * 5'
    - cron: '58 0 * * 5'
    - cron: '00 1 * * 5'
jobs:
  job_update_db:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '18'
      
      - name: gogogo
        run: |
          npm install -g coffeescript
          npm install
          coffee update_db.coffee
